'use strict';
import { isDOMElement, PREFIX, OPERATORS } from './utils';
import { PARSE_FUNCS, DEFAULT_FUNC } from './parse_funcs/index';
import pubsub from './pubsub';

let prepareConfig = function prepareConfig(input) {
  let config = {
    fields: typeof input.fields === 'object' ? input.fields : undefined,
    custom: typeof input.custom === 'object' ||
      typeof input.custom === 'string' ? input.custom : undefined,
    container: isDOMElement(input.container) ? input.container : undefined,
    parseFunc: typeof input.parseFunc === 'function' ? input.parseFunc :
      typeof input.parseFunc === 'string' &&
      typeof PARSE_FUNCS[input.parseFunc] === 'function' ?
      PARSE_FUNCS[input.parseFunc] : PARSE_FUNCS[DEFAULT_FUNC],
    id: input.id !== undefined ? parseInt(input.id, 10) : 0,
    operators: typeof input.operators === 'object' &&
      typeof input.operators.length === 'number' ? input.operators : OPERATORS,
    ps: pubsub(),
    conditions: []
  };

  //Ensure non-existing ID for autogenerated values
  if (typeof config.id === 'number') {
    let el;
    do {
      config.id += 1;
      el = document.getElementById(`${PREFIX}${config.id}`);
    } while (el);
    config.id = parseInt(config.id, 10);
  }

  if ((!config.fields && !config.custom) || !config.container) {
    throw 'Params `fields/custom` and `container` are mandarory';
  }

  if (config.fields === undefined && config.custom) {
    config.customMode = true;
  }

  return config;
};

export default prepareConfig;
